[package]
name = "garden"
version = "0.1.0"
edition = "2018"

[features]
debug_port_e9 = []
debug_vga = []

[dependencies]
spin = "0.9.3"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]