[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"] # provides mem{cmp,cpy,move,set}

[build]
target = "x86_64-kernel.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"